version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      # build the application image
      - run: docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH .

      # log to registry
      - run: |
          docker login --username=_ --password=${HEROKU_TOKEN} registry.heroku.com

      # deploy the image
      - run: docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH

      # tag the image
      - run: docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 registry.heroku.com/$CIRCLE_PROJECT_REPONAME/web

      # release
      - run: APP_NAME=$CIRCLE_PROJECT_REPONAME source heroku-release.sh
