version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout

      # build the application image
      - run: docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 .

      # log to registry
      - run: docker login --username=_ --password=${HEROKU_TOKEN} registry.heroku.com

      # tag the image
      - run: |
          docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 \
          registry.heroku.com/$CIRCLE_PROJECT_REPONAME/web

      # release
      - run: APP_NAME=$CIRCLE_PROJECT_REPONAME source heroku-release.sh
